# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'hcidweb-svc-acr'
    repository: '$(imageRepository)'
    command: build
    Dockerfile: 'app/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: 'hcidweb-svc-acr'
    repository: '$(imageRepository)'
    command: push
    tags: |
      $(Build.BuildId)
    
    